# Generated by Django 4.0.4 on 2022-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_follow_followers_alter_follow_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
