# Generated by Django 4.0.4 on 2022-06-21 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postdata', '0007_remove_post_comment_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='post',
        ),
    ]
