# Generated by Django 4.0.4 on 2022-06-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.CharField(choices=[('accept', 'Accept'), ('panding', 'Panding')], default='pending', max_length=10),
        ),
    ]
